server:
  port: 9839
spring:
  data.mongodb.uri:
    mongodb://host.docker.internal:27017/oauth_xyz_rc

spring.data.rest.base-path: /api

oauth.xyz:
  root: http://host.docker.internal:9839/
  asEndpoint: http://host.docker.internal:9834/api/as/transaction
  rsEndpoint: http://host.docker.internal:9836/api/rs

# spring.devtools.restart.exclude: 

spring.jackson.default-property-inclusion: NON_NULL

spring.mvc.dispatch-options-request: true

server.servlet.session.cookie.path: /api/client
